DELETE http://localhost:3003/api/blogposts/5e75c1ae3b561222b0cec1dd
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG50aGV3aWNrZWQiLCJpZCI6IjVlNzM1OGI3NmU5YTdlMDdmNDY0OGM0MSIsImlhdCI6MTU4NDc3OTI3OH0.kEtpuPOHRfBqSCKC2A-oQLx43mTlgKp-8LDwG0IT6ag