DELETE http://localhost:3003/api/blogposts/5e75d29c288efc5468a44603
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG50aGV3aWNrZWQiLCJpZCI6IjVlNzM1OGI3NmU5YTdlMDdmNDY0OGM0MSIsImlhdCI6MTU4NDc3OTI3OH0.kEtpuPOHRfBqSCKC2A-oQLx43mTlgKp-8LDwG0IT6ag